TRUNCATE TABLE SPOPOFF.RolesLink ;
TRUNCATE TABLE SPOPOFF.MemberOf ;
TRUNCATE TABLE SPOPOFF.Members ;
TRUNCATE TABLE SPOPOFF.Permissions ;
DELETE FROM SPOPOFF.Role ;
DELETE FROM SPOPOFF.Groupe ;
TRUNCATE TABLE SPOPOFF.IDNT_ATTRS ;
TRUNCATE TABLE SPOPOFF.CPTE_ATTRS ;
TRUNCATE TABLE SPOPOFF.OBJS_ATTRS ;
TRUNCATE TABLE SPOPOFF.OBJS_HBLT ;
TRUNCATE TABLE SPOPOFF.OBJS_CPTE ;
TRUNCATE TABLE SPOPOFF.IDNT_CPTE ;
TRUNCATE TABLE SPOPOFF.CPTE_HBLT ;
DELETE FROM SPOPOFF.HABILITANT ;
DELETE FROM SPOPOFF.COMPTE ;
DELETE FROM SPOPOFF.OBJSECU ;
DELETE FROM SPOPOFF.IDENTITE ;
DELETE FROM SPOPOFF.DPT_IDNT_CPTE ;
DELETE FROM SPOPOFF.DPT ;


