 CREATE TABLE `techdecision`.`IDNT_ATTRS` (
`FKIDNT` INT( 11 ) NOT NULL ,
`ATTR` VARCHAR( 10 ) NOT NULL ,
`VAL` VARCHAR( 150 ) NOT NULL ,
`PKATTR_IDNT` INT( 12 ) NOT NULL AUTO_INCREMENT ,
PRIMARY KEY ( `PKATTR_IDNT` ) ,
INDEX ( `FKIDNT` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`CPTE_ATTRS` (
`FKCPTE` INT( 11 ) NOT NULL ,
`ATTR` VARCHAR( 10 ) NOT NULL ,
`VAL` VARCHAR( 150 ) NOT NULL ,
`PKATTR_CPTE` INT( 12 ) NOT NULL AUTO_INCREMENT ,
PRIMARY KEY ( `PKATTR_CPTE` ) ,
INDEX ( `FKCPTE` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`OBJS_ATTRS` (
`FKOBJS` INT( 11 ) NOT NULL ,
`ATTR` VARCHAR( 10 ) NOT NULL ,
`VAL` VARCHAR( 150 ) NOT NULL ,
`PKATTR_OBJS` INT( 12 ) NOT NULL AUTO_INCREMENT ,
PRIMARY KEY ( `PKATTR_OBJS` ) ,
INDEX ( `FKOBJS` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`IDENTITE` (
`PKIDNT` INT( 11 ) NOT NULL ,
`USERNAME` VARCHAR( 30 ) NOT NULL ,
`FONCTION` VARCHAR( 30 ) NOT NULL ,
`DEPARTEMENT` VARCHAR( 30 ) NOT NULL,
 PRIMARY KEY ( `PKIDNT` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`COMPTE` (
`PKCPTE` INT( 11 ) NOT NULL ,
`PKCPTE2` INT( 11 ) NOT NULL ,
 PRIMARY KEY ( `PKCPTE` ) 
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`HABILITANT` (
`PKHBLT` INT( 11 ) NOT NULL ,
`VAL` VARCHAR( 100 ) NOT NULL ,
`TYPE` INT( 11 ) ,
 PRIMARY KEY ( `PKHBLT` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`OBJSECU` (
`PKOBJS` INT( 11 ) NOT NULL ,
 PRIMARY KEY ( `PKOBJS` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`OBJS_HBLT` (
`FKOBJS` INT( 11 ) NOT NULL ,
`FKHBLT` INT( 11 ) NOT NULL ,
`PKOBJS_HBLT` INT( 12 ) NOT NULL AUTO_INCREMENT ,
 PRIMARY KEY ( `PKOBJS_HBLT` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`OBJS_CPTE` (
`FKOBJS` INT( 11 ) NOT NULL ,
`FKCPTE` INT( 11 ) NOT NULL ,
`PKOBJS_CPTE` INT( 12 ) NOT NULL AUTO_INCREMENT ,
 PRIMARY KEY ( `PKOBJS_CPTE` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`IDNT_CPTE` (
`FKIDNT` INT( 11 ) NOT NULL ,
`FKCPTE` INT( 11 ) NOT NULL ,
`PKIDNT_CPTE` INT( 12 ) NOT NULL AUTO_INCREMENT ,
 PRIMARY KEY ( `PKIDNT_CPTE` )
) ENGINE = InnoDB ;

 CREATE TABLE `techdecision`.`CPTE_HBLT` (
`FKCPTE` INT( 11 ) NOT NULL ,
`FKHBLT` INT( 11 ) NOT NULL ,
`PKCPTE_HBLT` INT( 12 ) NOT NULL AUTO_INCREMENT ,
 PRIMARY KEY ( `PKCPTE_HBLT` )
) ENGINE = InnoDB ;

ALTER TABLE IDNT_ATTRS ADD CONSTRAINT AA1234 FOREIGN KEY (FKIDNT) REFERENCES IDENTITE (PKIDNT);
ALTER TABLE CPTE_ATTRS ADD CONSTRAINT AB1234 FOREIGN KEY (FKCPTE) REFERENCES COMPTE (PKCPTE);
ALTER TABLE OBJS_ATTRS ADD CONSTRAINT AC1234 FOREIGN KEY (FKOBJS) REFERENCES OBJSECU (PKOBJS);
ALTER TABLE OBJS_HBLT ADD CONSTRAINT AD1234 FOREIGN KEY (FKOBJS) REFERENCES OBJSECU (PKOBJS);
ALTER TABLE OBJS_HBLT ADD CONSTRAINT AE1234 FOREIGN KEY (FKHBLT) REFERENCES HABILITANT (PKHBLT);
ALTER TABLE OBJS_CPTE ADD CONSTRAINT AF1234 FOREIGN KEY (FKOBJS) REFERENCES OBJSECU (PKOBJS);
ALTER TABLE OBJS_CPTE ADD CONSTRAINT AG1234 FOREIGN KEY (FKCPTE) REFERENCES COMPTE (PKCPTE);
ALTER TABLE IDNT_CPTE ADD CONSTRAINT AH1234 FOREIGN KEY (FKIDNT) REFERENCES IDENTITE (PKIDNT);
ALTER TABLE IDNT_CPTE ADD CONSTRAINT AI1234 FOREIGN KEY (FKCPTE) REFERENCES COMPTE (PKCPTE);
ALTER TABLE CPTE_HBLT ADD CONSTRAINT AJ1234 FOREIGN KEY (FKHBLT) REFERENCES HABILITANT (PKHBLT);
ALTER TABLE CPTE_HBLT ADD CONSTRAINT AK1234 FOREIGN KEY (FKCPTE) REFERENCES COMPTE (PKCPTE);
